on: push
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    # - uses: actions/setup-node@v3
    #   with:
    #     node-version: 16
    # - run: npm install-ci-test
    # - uses:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.5'
    - name: Install conan2
      uses: turtlebrowser/get-conan@main
    - name: Install repo
      run: |
        conan install .
    - name: Running checks
      # run: |
      #   source $VENV  
      #   bash checks.sh
      run: |
        bash checks.sh merge
  # publish:
  #   needs: [test]
  #   steps:
  #   - uses: actions/checkout@v4
